name: Backup Jellyfin Docker Image

on:
  workflow_dispatch:

jobs:
  pull-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Pull jellyfin
        run: docker pull jellyfin/jellyfin:latest

      - name: Save to tar
        run: docker save -o jellyfin.tar jellyfin/jellyfin:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jellyfin-docker-image
          path: jellyfin.tar
